server:
  port: 5001

spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/airline_user_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwt:
    secret: ${JWT_SECRET:qwdfghjhsxcvbnjhgfyfdcmsdfdcvbjhfdcvbnjhgfcvbnmdfghjhgfdcvngszxcvbnndfnbvsdcvhytdfhjmb}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}


