server:
  port: 5004

spring:
  application:
    name: location-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_location_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver